### ISSUE TITLE
Bug: build github action failing

### ISSUE THREAD

**Issue by sliedig** [aws-samples/aws-serverless-developer-experience-workshop-typescript#10]
### Expected Behaviour

Build should pass

### Current Behaviour

Build does not pass due to miss configured gh action

### Code snippet

```csharp
NA
```

### Steps to Reproduce

NA

**Comment by Kevinwochan** [comment]
fixed in https://github.com/aws-samples/aws-serverless-developer-experience-workshop-typescript/pull/12
