### ISSUE TITLE
Bug: template.yaml is not deployable

### ISSUE THREAD

**Issue by fedor-pavlov** [aws-samples/aws-serverless-developer-experience-workshop-typescript#54]
### Expected Behaviour

`sam deploy`
should lead to successful deployment

### Current Behaviour

`sam deploy`
produced error:
`Error: Failed to create changeset for the stack: uni-prop-local-contracts, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: [/Resources/ContractsTableStreamToEventPipe/Type/SourceParameters/DynamoDBStreamParameters] 'null' values are not allowed in templates`

### Code snippet

```csharp
sam deploy

                Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-yu9dziyvptkw
                A different default S3 bucket can be set in samconfig.toml
                Or by specifying --s3-bucket explicitly.
File with same data already exists at uni-prop-local-contracts/6cc61cdc11a1db27c197342a0f2461c4, skipping upload
File with same data already exists at uni-prop-local-contracts/d280835f54ec7e9b01096ed38c8dd4c7, skipping upload
File with same data already exists at uni-prop-local-contracts/453284e83228f68a2bd571ef9cf601a8.template, skipping upload
File with same data already exists at uni-prop-local-contracts/3ffa68cf01c3b07b5e8ebde79a8b0918.template, skipping upload

        Deploying with following values
        ===============================
        Stack name                   : uni-prop-local-contracts
        Region                       : us-west-2
        Confirm changeset            : False
        Disable rollback             : True
        Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-yu9dziyvptkw
        Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
        Parameter overrides          : {"Stage": "local"}
        Signing Profiles             : {}

Initiating deployment
=====================

File with same data already exists at uni-prop-local-contracts/a68ada9b53b1e0e327df3a4aba53f7fa.template, skipping upload


Waiting for changeset to be created..

Error: Failed to create changeset for the stack: uni-prop-local-contracts, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: [/Resources/ContractsTableStreamToEventPipe/Type/SourceParameters/DynamoDBStreamParameters] 'null' values are not allowed in templates
```

### Steps to Reproduce

1) copy-paste template.yaml into workshop environment
2) run `sam deploy`

**Comment by Kevinwochan** [comment]
@fedor-pavlov Thanks, investigating this now

**Comment by fedor-pavlov** [comment]
@Kevinwochan Thank you for the blasting-flast reaction! It does help indeed.

**Comment by fedor-pavlov** [comment]
The correct steps to reproduce should be:

## Steps to Reproduce
```
git clone https://github.com/aws-samples/aws-serverless-developer-experience-workshop-typescript.git unicorn_reference
cd unicorn_reference
cd unicorn_contracts
sam build
sam deploy
```

If I follow this path, the deployment finished correctly.

**Comment by fedor-pavlov** [comment]
In order to help those who'll face the same issue with the workshop in the future:

1) watch out YAML example in the workshop book: it's actually incorrect, check yourself
2) don't forget to run `sam build` after correction of template.yaml file before you run `sam deploy`:
```
sam build
sam deploy
```

**Comment by fedor-pavlov** [comment]
The repository is correct, no issues here

**Comment by Kevinwochan** [comment]
Great to hear you got it working!
And thank you for contributing to our documentation, I have no doubt other customers will run into a similar issue so making those error messages searchable has improved the content.
We’ll update the workshop instructions to make the SAM build commands more obvious.
